In [1]:
import torch
from torch import nn
from torch.nn import functional as F

In [2]:
class CenteredLayer(nn.Module):
  def __init__(self):
    super().__init__()
  def forward(self,X):
    return X-X.mean()

In [3]:
layer=CenteredLayer()
layer(torch.tensor([1.0,2,3,4,5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [4]:
net=nn.Sequential(nn.LazyLinear(128),CenteredLayer())


In [5]:
Y=net(torch.rand(4,8))
Y.mean()

tensor(-2.3283e-09, grad_fn=<MeanBackward0>)

In [6]:
class MyLinear(nn.Module):
  def __init__(self,in_units,units):
    super().__init__()
    self.weight=nn.Parameter(torch.randn(in_units,units))
    self.bias=nn.Parameter(torch.zeros(units,))
  def forward(self,X):
    linear= torch.matmul(X,self.weight)+self.bias
    return F.relu(linear)

In [7]:
linear=MyLinear(5,3)
linear.weight


Parameter containing:
tensor([[ 0.5476, -0.8779,  0.4269],
        [ 0.2027,  0.1648, -0.1468],
        [-0.4187, -0.3046,  1.8995],
        [-0.7491, -0.0404, -0.1914],
        [ 0.6311, -0.8873,  1.2935]], requires_grad=True)

In [9]:
linear(torch.rand(2,5))

tensor([[2.1770, 0.0000, 0.0000],
        [2.4339, 1.6521, 0.0000]], grad_fn=<ReluBackward0>)

In [12]:
net=nn.Sequential(MyLinear(64,8),MyLinear(8,1))
net(torch.randn(2,64))

tensor([[0.],
        [0.]], grad_fn=<ReluBackward0>)