In [1]:
import torch
from torch import nn
from torch.nn import functional as F

x=torch.arange(4)
torch.save(x,'x-file')

In [2]:
x2=torch.load('x-file')
x2

tensor([0, 1, 2, 3])

In [3]:
y=torch.zeros(4)
torch.save([x,y],'x-files')
x2,y2=torch.load('x-files')
(x2,y2)

(tensor([0, 1, 2, 3]), tensor([0., 0., 0., 0.]))

In [4]:
mydict={'x':x,'y':y}
torch.save(mydict,'mydict')
mydict2=torch.load('mydict')
mydict2

{'x': tensor([0, 1, 2, 3]), 'y': tensor([0., 0., 0., 0.])}

In [5]:
class MLP(nn.Module):
  def __init__(self):
    super().__init__()
    self.hidden=nn.Linear(20,256)
    self.output=nn.Linear(256,10)
  def forward(self,x):
    return self.output(F.relu(self.hidden(x)))

net=MLP()
X=torch.randn(2,20)
Y=net(X)
print(Y)

tensor([[-0.0801, -0.0131,  0.0038, -0.0354, -0.1040, -0.4422,  0.0947, -0.4762,
          0.2046, -0.1676],
        [-0.1545, -0.0989, -0.1929,  0.3021, -0.1773, -0.2068,  0.4777,  0.2484,
         -0.1633,  0.0485]], grad_fn=<AddmmBackward0>)


In [6]:
torch.save(net.state_dict(), "mlp.params")

In [7]:
clone=MLP()
clone.load_state_dict(torch.load("mlp.params"))
clone

MLP(
  (hidden): Linear(in_features=20, out_features=256, bias=True)
  (output): Linear(in_features=256, out_features=10, bias=True)
)

In [8]:
Y_clone=clone(X)
Y_clone==Y

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])